apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-config

data:
  POSTGRES_DB: postgres
  POSTGRES_HOST: supabase-db
  POSTGRES_PORT: "5432"
  STUDIO_DEFAULT_ORGANIZATION: "MonOrganisation"
  STUDIO_DEFAULT_PROJECT: "MonProjet"
  SITE_URL: "http://localhost"
  API_EXTERNAL_URL: "http://localhost:8000"
  SUPABASE_PUBLIC_URL: "http://localhost:8000"
  ENABLE_EMAIL_SIGNUP: "true"
  ENABLE_ANONYMOUS_USERS: "false"
  ENABLE_EMAIL_AUTOCONFIRM: "true"
  ENABLE_PHONE_SIGNUP: "false"
  ENABLE_PHONE_AUTOCONFIRM: "false"
  PGRST_DB_SCHEMAS: "public,storage"
  JWT_EXPIRY: "3600"
  MAILER_URLPATHS_INVITE: "/auth/invite"
  MAILER_URLPATHS_CONFIRMATION: "/auth/confirm"
  MAILER_URLPATHS_RECOVERY: "/auth/recover"
  MAILER_URLPATHS_EMAIL_CHANGE: "/auth/email-change" 